# Generated by Django 2.2.5 on 2019-10-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='author',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='email',
            field=models.EmailField(default='bien', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentaire',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_single',
            field=models.ImageField(upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='image',
            field=models.ImageField(upload_to='blog'),
        ),
    ]
