# Generated by Django 2.2.5 on 2019-10-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191019_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_commentaire', to='blog.Article'),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='image',
            field=models.ImageField(default='blog/24.jpg', upload_to='blog'),
        ),
    ]
