# Generated by Django 2.2.5 on 2019-10-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191019_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
